# Home Assistant add-on: RV Link
name: "RV Link"
version: "0.2.0"
slug: "rv-link"
description: "Deploys and updates Node-RED automation project for RV monitoring and control."
url: "https://github.com/Backroads4Me/ha-addons-alpha"
maintainer: "Ted Lanham <tedlanham@gmail.com>"
arch:
  - aarch64
  - amd64
  - armv7
startup: once
boot: manual
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: false
map:
  - share:rw
  - addon_configs:rw
options:
  force_update: true
schema:
  force_update: bool?
image: ghcr.io/backroads4me/{arch}-rv-link{SUFFIX}
